package ru.skittens.goroute.ui.navigation

enum class Destinations(val title: String? = "") {
    Splash,
    OnBoarding,
    Authentication,
    Registration,
    MainEmployee,
    MainAdmin,
    MainTourist,
    Routes,
    NewRoute("Новый поход"),
    EndedRoutes,
    SelectRoute(null),
    FiltersRoutes("Фильтры"),
    SelectParkOrSight("Новый поход"),
    AddGroup("Новая группа"),
    Group,
    Permission("Заявка на разрешение"),
    AddIncident,
    Map("Карта"),
    NewsFriends("Лента новостей"),
    Profile("Профиль"),
    ListFriends("Список друзей"),
    Rating("Рейтинг"),
    Achievement("Достижения"),
    Event("Точка интереса"),
    AllIncidents,
    MapEmployee,
    ProfileEmployee
}